# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

def shared_pods

  # Pods for Customer

  pod 'IQKeyboardManagerSwift', :git => 'https://github.com/FarhanAnsari92/IQKeyboardManager.git'
  pod 'NHRangeSlider', :git => 'https://github.com/FarhanAnsari92/NHRangeSlider.git'
  pod "ZSWTappableLabel", "~> 3.3"
  
  # https://github.com/jonkykong/SideMenu
  pod 'SideMenu', '~> 6.0'
  
  # https://github.com/Friend-LGA/LGSideMenuController
  pod 'LGSideMenuController'
  
  # https://developers.google.com/maps/documentation/ios-sdk/start
  pod 'GoogleMaps', '2.5.0'
  
  # https://github.com/Alamofire/Alamofire
  pod 'Alamofire', '~> 4.8.2'

  # https://github.com/SwiftyJSON/Alamofire-SwiftyJSON
  pod 'Alamofire-SwiftyJSON'

  # https://github.com/Hearst-DD/ObjectMapper
  pod 'ObjectMapper', '~> 3.4'
  
  # https://github.com/ninjaprox/NVActivityIndicatorView
  pod 'NVActivityIndicatorView'

  # https://github.com/jdg/MBProgressHUD
  pod 'MBProgressHUD', '~> 1.1.0'

  # https://github.com/SDWebImage/SDWebImage
  pod 'SDWebImage', '~> 5.8.3'
  
  pod 'TTTAttributedLabel'
  
  # https://github.com/KennethTsang/GrowingTextView
  pod 'GrowingTextView', '0.7.2'
  # https://github.com/mohn93/AdvancedPageControl
  pod 'AdvancedPageControl'
  
  # https://github.com/rushisangani/RSSelectionMenu
  pod 'RSSelectionMenu', '~> 7.1.3'

end

target 'Customer' do
  shared_pods
end

target 'Mechanic' do
  shared_pods
end
